// 💀⚡💀 DO NOT EDIT THIS FILE 💀⚡💀 DO NOT EDIT THIS FILE 💀⚡💀 DO NOT EDIT THIS FILE 💀⚡💀

/*////////////////////////////////////////////////////////////////////////////////////////////////

  ##### ##### ##### ##### |   This file is autogenerated using an Nx workspace schematic.
  #       #   #   # #   # |   Manual changes should not be needed. After adding your feature 
  #####   #   #   # ##### |   to software security, simply regenerate this file by running
      #   #   #   # #     |   `nx workspace-schematic update-dotnet-localization-files`. If there is an issue
  #####   #   ##### #     |   with the generated file, check tools/generators/update-dotnet-localization-files

////////////////////////////////////////////////////////////////////////////////////////////////*/

import { DotnetTemplate } from '../../models';

import { FieldNameMap as EnFieldMap } from './en';
import { FieldNameMap as CsFieldMap } from './cs';
import { FieldNameMap as DeFieldMap } from './de';
import { FieldNameMap as EsFieldMap } from './es';
import { FieldNameMap as FrFieldMap } from './fr';
import { FieldNameMap as ItFieldMap } from './it';
import { FieldNameMap as JaFieldMap } from './ja';
import { FieldNameMap as KoFieldMap } from './ko';
import { FieldNameMap as PlFieldMap } from './pl';
import { FieldNameMap as PtBRFieldMap } from './pt-BR';
import { FieldNameMap as RuFieldMap } from './ru';
import { FieldNameMap as TrFieldMap } from './tr';
import { FieldNameMap as ZhHansFieldMap } from './zh-Hans';
import { FieldNameMap as ZhHantFieldMap } from './zh-Hant';

export const CombinedFieldMap = {
  ...EnFieldMap,
  ...CsFieldMap,
  ...DeFieldMap,
  ...EsFieldMap,
  ...FrFieldMap,
  ...ItFieldMap,
  ...JaFieldMap,
  ...KoFieldMap,
  ...PlFieldMap,
  ...PtBRFieldMap,
  ...RuFieldMap,
  ...TrFieldMap,
  ...ZhHansFieldMap,
  ...ZhHantFieldMap,
} as unknown as Record<string, keyof DotnetTemplate>;
