// 💀⚡💀 DO NOT EDIT THIS FILE 💀⚡💀 DO NOT EDIT THIS FILE 💀⚡💀 DO NOT EDIT THIS FILE 💀⚡💀

/*////////////////////////////////////////////////////////////////////////////////////////////////

  ##### ##### ##### ##### |   This file is autogenerated using an Nx workspace schematic.
  #       #   #   # #   # |   Manual changes should not be needed. After adding your feature 
  #####   #   #   # ##### |   to software security, simply regenerate this file by running
      #   #   #   # #     |   `nx workspace-schematic update-dotnet-localization-files`. If there is an issue
  #####   #   ##### #     |   with the generated file, check tools/generators/update-dotnet-localization-files

////////////////////////////////////////////////////////////////////////////////////////////////*/

export const FieldNameMap = {
  Язык: 'languages',
  'Короткое имя': 'shortNames',
  Теги: 'tags',
  'Имя шаблона': 'templateName',
  Шаблоны: 'templateName',
};
